development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror-shopping-site_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror-shopping-site_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ror-shopping-site_production
  pool: 5
  username: root
  password: root
  host: localhost
 